import time
from selenium.webdriver.common.by import By
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.select import Select
from selenium.webdriver.support.wait import WebDriverWait
from Locaters.auto_page import Auto
from Locaters.header_page import Header
from Generic.Comman_functions import add_time
from Locaters.legal_page import Legal
from Locaters.party_page import Party



driver = webdriver.Chrome()
# driver = webdriver.Chrome('C:\\Users\\Sagar\\Webkeying\\chromedriver_win32\\chromedriver.exe')
driver.maximize_window()
time.sleep(1)
driver.get("https://mercury.unidex.ai/auth/login")
waits = WebDriverWait(driver, 10)
time.sleep(5)
# email= By.XPATH, f"//input[@placeholder='Email"
# waits.until(EC.presence_of_element_located(email))
email = driver.find_element(By.XPATH, "//input[@placeholder='Email']")
email.clear()
email.send_keys("Sagar@stellaripl.com")
password = driver.find_element(By.XPATH, "//input[@placeholder='Password']")
password.clear()
password.send_keys("Sagar@4483")
login = driver.find_element(By.XPATH, "//button[contains(text(), ' Log In ')]")
login.click()
time.sleep(15)
driver.find_element(By.XPATH, "//a[@class='dropdown-toggle text-dark px-2 pb-2 fw-bold']").click()
time.sleep(4)
driver.find_element(By.XPATH, "//a[@class='dropdown-toggle text-dark px-2 pb-2 fw-bold']/..//button[7]").click()
time.sleep(5)
filter_search = driver.find_element(By.XPATH, "//input[@placeholder='Type to filter...']")
filter_search.clear()
batch_id = "11001-20240518-01"
filter_search.send_keys(batch_id)
driver.find_element(By.XPATH, "//app-ida-table/div[2]/div/div[3]/div/button/i").click()
batch = By.XPATH, f"//a[contains(text(), '{batch_id}')]"
waits.until(EC.presence_of_element_located(batch))
time.sleep(5)
s = Select(driver.find_element(By.XPATH, f"//a[contains(text(), '{batch_id}')]/../../following-sibling::datatable-body-cell/div/div/select[1]"))
s.select_by_visible_text('DEED')
summary_button = driver.find_element(By.XPATH, "//button[contains(text(), ' Summary ')]")
time.sleep(1)
summary_button.click()
time.sleep(2)
driver.find_element(By.XPATH, "//input[@placeholder='Img name']").clear()
time.sleep(2)
driver.find_element(By.XPATH, "//input[@placeholder='Img name']").send_keys("DCDIST-2024_00043716")
time.sleep(5)
driver.find_element(By.LINK_TEXT, "DCDIST-2024_00043716").click()
time.sleep(15)
driver.switch_to.window(driver.window_handles[1])
s = Select(driver.find_element(By.XPATH, "//label[contains(text(), ' Document Type ')]/..//select"))
s.select_by_visible_text('DE-Deed')
date = driver.find_element(By.XPATH, Auto.recording_date)
if date.is_enabled():
    date.clear()
    time.sleep(2)
    date.send_keys("03/25/1998")
else:
    print("Recording date field is disabled" + date.get_attribute("value"))

b = driver.find_element(By.XPATH, Auto.book)
if b.is_enabled():
    b.clear()
    b.send_keys("12345")
else:
    print("Book number field is disabled    " + b.get_attribute("value"))
p = driver.find_element(By.XPATH, Auto.page)
if p.is_enabled():
    p.clear()
    p.send_keys("12345")
else:
    print("Page number field is disabled    " + p.get_attribute("value"))
def numbers(v,list):
    l = driver.find_element(By.XPATH, v)
    # data = l.text

    for i in list:
        l.clear()
        l.send_keys(i)
        time.sleep(1)
        data = l.get_attribute("value")
        # print(data)
        if data == i and len(data) == len(i):
            print("Both the value same Pass")
        else:
            print("Both the value is different Fail")
        time.sleep(1)
d = Auto.document_number
d1 = ['ndn 283-e:', '','2233','swqd','@##dsd']
numbers(d,d1)
# if d.is_enabled():
#     d.clear()
#     d.send_keys("1283-89873:894  ASed")
# else:
#     print("Document number field is disabled")
s = driver.find_element(By.XPATH, Auto.state)
if s.is_enabled():
    s.clear()
    s.send_keys("WA")
else:
    print("State field is disabled  " + s.get_attribute("value"))
c = driver.find_element(By.XPATH, Auto.county_name)
if c.is_enabled():
    c.clear()
    c.send_keys("King")
else:
    print("County field is disabled     " + c.get_attribute("value"))
fi = driver.find_element(By.XPATH, Auto.fips)
if fi.is_enabled():
   fi.clear()
   fi.send_keys("King")
else:
    print("FIPS field is disabled   " + fi.get_attribute("value"))
ded = driver.find_element(By.XPATH, Auto.data_entry_date)
if ded.is_enabled():
   ded.clear()
   ded.send_keys("12/31/2023")
else:
    print("Data entry date field is disabled    " + ded.get_attribute("value"))
ri = driver.find_element(By.XPATH, Auto.record_id)
if ri.is_enabled():
   ri.clear()
   ri.send_keys("A")
else:
    print("Record ID field is disabled  " + ri.get_attribute("value"))
rt = driver.find_element(By.XPATH, Auto.record_type)
if rt.is_enabled():
   rt.clear()
   rt.send_keys("B")
else:
    print("Record Type field is disabled    " + rt.get_attribute("value"))
dsc= driver.find_element(By.XPATH, Auto.data_source_code)
if dsc.is_enabled():
   dsc.clear()
   dsc.send_keys("123")
else:
    print("Data Source code field is disabled   " + dsc.get_attribute("value"))
time.sleep(5)
driver.save_screenshot('./screenshots/auto_screenshot.png')
add_time('./screenshots/auto_screenshot.png')
# # driver.find_element(By.XPATH, Auto.autoform_submit).click()
# # time.sleep(2)
# # driver.find_element(By.XPATH, Auto.autoform_submit).click()
# time.sleep(2)
# er = driver.find_element(By.XPATH, Auto.enter_reason)
# if er.is_enabled():
#     # er.clear()
#     # er.click()
#     er.send_keys("test")
#     time.sleep(2)
#     driver.find_element(By.XPATH, Auto.enter_reason_save).click()
# else:
#     pass
time.sleep(2)
driver.save_screenshot('./screenshots/auto_screenshot1.png')
add_time('./screenshots/auto_screenshot1.png')
driver.find_element(By.XPATH, Header.header_form).click()
cd = driver.find_element(By.XPATH, Header.contract_date)
if cd.is_enabled():
    cd.clear()
    cd.send_keys("02/12/2023")
else:
    print("Contract date field is disabled")
driver.find_element(By.XPATH, Header.sales_price).clear()
driver.find_element(By.XPATH, Header.sales_price).send_keys("12345")
s = Select(driver.find_element(By.XPATH, Header.sales_price_code))
s.select_by_value("1: D")
driver.find_element(By.XPATH, Header.city_transfer_tax).clear()
driver.find_element(By.XPATH, Header.city_transfer_tax).send_keys("1234.50")
driver.find_element(By.XPATH, Header.county_transfer_tax).clear()
driver.find_element(By.XPATH, Header.county_transfer_tax).send_keys("1234.50")
driver.find_element(By.XPATH, Header.total_transfer_tax).clear()
driver.find_element(By.XPATH, Header.total_transfer_tax).send_keys("1234.50")
driver.find_element(By.XPATH, Header.title_company_name).clear()
driver.find_element(By.XPATH, Header.title_company_name).send_keys("SKH DJNJJ7 383287wy4782fd 10")
driver.find_element(By.XPATH, Header.wa_excise_tax).clear()
driver.find_element(By.XPATH, Header.wa_excise_tax).send_keys("1234567")
driver.find_element(By.XPATH, Header.mtg_due_date).clear()
driver.find_element(By.XPATH, Header.mtg_due_date).send_keys("02/12/2000")
driver.find_element(By.XPATH, Header.mtg_interest_rate).clear()
driver.find_element(By.XPATH, Header.mtg_interest_rate).send_keys("02/12/2000")
driver.find_element(By.XPATH, Header.mtg_lender_name).clear()
driver.find_element(By.XPATH, Header.mtg_lender_name).send_keys("MERS")
driver.find_element(By.XPATH, Header.mtg_loan_amount).send_keys("82832")
s = Select(driver.find_element(By.XPATH, Header.mtg_loan_type))
s.select_by_value("4: D")
s = Select(driver.find_element(By.XPATH, Header.mtg_type_financing))
s.select_by_value("7: VAR")
driver.find_element(By.XPATH, Header.doc_bkpg_concurrent_mortgage).clear()
driver.find_element(By.XPATH, Header.doc_bkpg_concurrent_mortgage).send_keys("124445")
# driver.find_element(By.XPATH, Header.lender_mail_zip).clear()
# driver.find_element(By.XPATH, Header.lender_mail_zip).send_keys("12345")
driver.find_element(By.XPATH, Header.interest_only_flag).clear()
driver.find_element(By.XPATH, Header.interest_only_flag).send_keys("12")
time.sleep(2)
driver.find_element(By.XPATH, Header.adjustable_rider).click()
time.sleep(1)
driver.find_element(By.XPATH, Header.first_change_date).clear()
driver.find_element(By.XPATH, Header.first_change_date).send_keys("122624")
driver.find_element(By.XPATH, Header.change_date_greater).clear()
driver.find_element(By.XPATH, Header.change_date_greater).send_keys("12.3")
driver.find_element(By.XPATH, Header.change_date_less_than).clear()
driver.find_element(By.XPATH, Header.change_date_less_than).send_keys("12.3")
driver.find_element(By.XPATH, Header.change_index).clear()
driver.find_element(By.XPATH, Header.change_index).send_keys("12.3")
driver.find_element(By.XPATH, Header.maximum_interest_rate).clear()
driver.find_element(By.XPATH, Header.maximum_interest_rate).send_keys("12.3")
s = Select(driver.find_element(By.XPATH, Header.adj_rate_index))
s.select_by_value("3: LIBOR3MO")
s = Select(driver.find_element(By.XPATH, Header.rate_change_frequency))
s.select_by_value("1: M")
s = Select(driver.find_element(By.XPATH, Header.fixed_step_rate_rider))
s.select_by_value("3: F")
time.sleep(2)
driver.save_screenshot("./screenshots/adjustable_rider_screenshot.png")
add_time('./screenshots/adjustable_rider_screenshot.png')
driver.find_element(By.XPATH, Header.attorney_name).clear()
driver.find_element(By.XPATH, Header.attorney_name).send_keys("dder 37374")
driver.find_element(By.XPATH, Header.attorney_name_list).clear()
driver.find_element(By.XPATH, Header.attorney_name_list).send_keys("dder 37374")
driver.find_element(By.XPATH, Header.escrow_number).clear()
driver.find_element(By.XPATH, Header.escrow_number).send_keys("dder 37374")
driver.find_element(By.XPATH, Header.escrow_officer_intials).clear()
driver.find_element(By.XPATH, Header.escrow_officer_intials).send_keys("dder 37374")
driver.find_element(By.XPATH, Header.title_company_department).clear()
driver.find_element(By.XPATH, Header.title_company_department).send_keys("dder 37374")
driver.find_element(By.XPATH, Header.title_company_2010).clear()
driver.find_element(By.XPATH, Header.title_company_2010).send_keys("dder 37374")
driver.find_element(By.XPATH, Header.title_company_branch_location).clear()
driver.find_element(By.XPATH, Header.title_company_branch_location).send_keys("dder 37374")
driver.find_element(By.XPATH, Header.attorney_name).clear()
driver.find_element(By.XPATH, Header.attorney_name).send_keys("dder 37374")
driver.find_element(By.XPATH, Header.title_company_name_shown_on_document).clear()
driver.find_element(By.XPATH, Header.title_company_name_shown_on_document).send_keys("dder 37374")
driver.find_element(By.XPATH, Header.title_company_name_selected_from_list_or_parsed).clear()
driver.find_element(By.XPATH, Header.title_company_name_selected_from_list_or_parsed).send_keys("dder 37374")
driver.find_element(By.XPATH, Header.title_company_name_source_code).clear()
driver.find_element(By.XPATH, Header.title_company_name_source_code).send_keys("dder 37374")
driver.find_element(By.XPATH, Header.title_only).clear()
driver.find_element(By.XPATH, Header.title_only).send_keys("dder 37374")
driver.find_element(By.XPATH, Header.title_order_number).clear()
driver.find_element(By.XPATH, Header.title_order_number).send_keys("dder 37374")
time.sleep(2)
driver.save_screenshot("./screenshots/header_title_company_addendum.png")
add_time('./screenshots/header_title_company_addendum.png')
time.sleep(5)
driver.find_element(By.XPATH, Legal.legal_form).click()
time.sleep(2)
apn = driver.find_element(By.XPATH, Legal.apn_1st)
apn.location_once_scrolled_into_view
time.sleep(2)
apn.clear()
driver.find_element(By.XPATH, Legal.apn_1st).send_keys("djd u3-,.ddw;:23")
driver.find_element(By.XPATH, Legal.add_apn).click()
driver.find_element(By.XPATH, Legal.apn_2nd).clear()
driver.find_element(By.XPATH, Legal.apn_2nd).send_keys("djd u3-,.ddw;:23")
driver.find_element(By.XPATH, Legal.tax_id_number).clear()
driver.find_element(By.XPATH, Legal.tax_id_number).send_keys("djd u3-,.ddw;:23")
driver.find_element(By.XPATH, Legal.property_address).clear()
driver.find_element(By.XPATH, Legal.property_address).send_keys("dbhjd 283-/&s 22")
driver.find_element(By.XPATH, Legal.property_unit).clear()
driver.find_element(By.XPATH, Legal.property_unit).send_keys("d-,& 3")
driver.find_element(By.XPATH, Legal.property_city).clear()
driver.find_element(By.XPATH, Legal.property_city).send_keys("New York")
s = Select(driver.find_element(By.XPATH, Legal.property_state))
s.select_by_visible_text("AS")
driver.find_element(By.XPATH, Legal.property_zip).clear()
driver.find_element(By.XPATH, Legal.property_zip).send_keys("02345")
driver.find_element(By.XPATH, Legal.property_zip4).clear()
driver.find_element(By.XPATH, Legal.property_zip4).send_keys("2345")
driver.save_screenshot("./screenshots/Legal_property_screenshot.png")
add_time('./screenshots/Legal_property_screenshot.png')
driver.find_element(By.XPATH, Legal.legal_lot).clear()
driver.find_element(By.XPATH, Legal.legal_lot).send_keys("d, -&1e")
driver.find_element(By.XPATH, Legal.legal_block).clear()
driver.find_element(By.XPATH, Legal.legal_block).send_keys("d, -&1e")
driver.find_element(By.XPATH, Legal.legal_section).clear()
driver.find_element(By.XPATH, Legal.legal_section).send_keys("d, -&1e")
driver.find_element(By.XPATH, Legal.legal_unit).clear()
driver.find_element(By.XPATH, Legal.legal_unit).send_keys("d, -&1e")
driver.find_element(By.XPATH, Legal.legal_phase_number).clear()
driver.find_element(By.XPATH, Legal.legal_phase_number).send_keys("d, -&1e")
driver.find_element(By.XPATH, Legal.legal_subdivision).clear()
driver.find_element(By.XPATH, Legal.legal_subdivision).send_keys("d, -&1e")
driver.find_element(By.XPATH, Legal.legal_map_reference).clear()
driver.find_element(By.XPATH, Legal.legal_map_reference).send_keys("d, -&1e")
driver.find_element(By.XPATH, Legal.legal_city_muni_town).clear()
driver.find_element(By.XPATH, Legal.legal_city_muni_town).send_keys("d, -&1e")
driver.find_element(By.XPATH, Legal.legal_tract_number).clear()
driver.find_element(By.XPATH, Legal.legal_tract_number).send_keys("d, -&1e")
driver.find_element(By.XPATH, Legal.legal_district).clear()
driver.find_element(By.XPATH, Legal.legal_district).send_keys("d, -&1e")
driver.find_element(By.XPATH, Legal.legal_land_lot).clear()
driver.find_element(By.XPATH, Legal.legal_land_lot).send_keys("d, -&1e")
driver.find_element(By.XPATH, Legal.legal_brief_desc).clear()
driver.find_element(By.XPATH, Legal.legal_brief_desc).send_keys("d, -&1e")
driver.find_element(By.XPATH, Legal.legal_section_twn_range_merid).clear()
driver.find_element(By.XPATH, Legal.legal_section_twn_range_merid).send_keys("d, -&1e")
s = Select(driver.find_element(By.XPATH, Legal.legal_lot_code))
s.select_by_value("2: MP")
driver.save_screenshot("./screenshots/legal_page.png")
add_time('./screenshots/legal_page.png')
time.sleep(2)
driver.find_element(By.XPATH, Party.party_form).click()
driver.find_element(By.XPATH, Party.first_middle_name).clear()
driver.find_element(By.XPATH, Party.first_middle_name).send_keys("SMITH D")
driver.find_element(By.XPATH, Party.last_corporation_name).clear()
driver.find_element(By.XPATH, Party.last_corporation_name).send_keys("JOHN")
s = Select(driver.find_element(By.XPATH, Party.id_code))
s.select_by_visible_text("ID-Individual(s)*")
time.sleep(1)
driver.find_element(By.XPATH, Party.seller_add_button).click()
driver.find_element(By.XPATH, Party.first_middle_name_2).clear()
driver.find_element(By.XPATH, Party.first_middle_name_2).send_keys("SMITH D")
driver.find_element(By.XPATH, Party.last_corporation_name_2).clear()
driver.find_element(By.XPATH, Party.last_corporation_name_2).send_keys("JOHN")
s = Select(driver.find_element(By.XPATH, Party.id_code_2))
s.select_by_visible_text("ID-Individual(s)*")
driver.find_element(By.XPATH, Party.seller_mail_address).clear()
driver.find_element(By.XPATH, Party.seller_mail_address).send_keys("bdbh ,-&/237 dn")
driver.find_element(By.XPATH, Party.seller_mail_unit).clear()
driver.find_element(By.XPATH, Party.seller_mail_unit).send_keys("d-,& 2")
driver.find_element(By.XPATH, Party.seller_mail_city).clear()
driver.find_element(By.XPATH, Party.seller_mail_city).send_keys("New York")
s = Select(driver.find_element(By.XPATH, Party.seller_mail_state_dropdown))
s.select_by_visible_text("OK")
driver.find_element(By.XPATH, Party.seller_mail_zip).clear()
driver.find_element(By.XPATH, Party.seller_mail_zip).send_keys("02340")
driver.find_element(By.XPATH, Party.seller_mail_zip4).clear()
driver.find_element(By.XPATH, Party.seller_mail_zip4).send_keys("2134")
driver.save_screenshot("./screenshots/party_seller_page.png")
add_time('./screenshots/party_seller_page.png')
driver.find_element(By.XPATH, Party.buyer_first_name).clear()
driver.find_element(By.XPATH, Party.buyer_first_name).send_keys("SMITH D")
driver.find_element(By.XPATH, Party.buyer_corp_name).clear()
driver.find_element(By.XPATH, Party.buyer_corp_name).send_keys("JOHN")
s = Select(driver.find_element(By.XPATH, Party.buyer_id_code))
s.select_by_visible_text("ID-Individual(s)*")
driver.find_element(By.XPATH, Party.buyer_care_of_name).clear()
driver.find_element(By.XPATH, Party.buyer_care_of_name).send_keys("JOHN")
s = Select(driver.find_element(By.XPATH, Party.buyer_visiting_code))
s.select_by_value("1: CR")
driver.find_element(By.XPATH, Party.buyer_mail_address).clear()
driver.find_element(By.XPATH, Party.buyer_mail_address).send_keys("bdbh ,-&/237 dn")
driver.find_element(By.XPATH, Party.buyer_mail_unit).clear()
driver.find_element(By.XPATH, Party.buyer_mail_unit).send_keys("d-,& 2")
driver.find_element(By.XPATH, Party.buyer_mail_city).clear()
driver.find_element(By.XPATH, Party.buyer_mail_city).send_keys("New York")
s = Select(driver.find_element(By.XPATH, Party.buyer_mail_state_dropdown))
s.select_by_visible_text("OK")
driver.find_element(By.XPATH, Party.buyer_mail_zip).clear()
driver.find_element(By.XPATH, Party.buyer_mail_zip).send_keys("02340")
driver.find_element(By.XPATH, Party.buyer_mail_zip4).clear()
driver.find_element(By.XPATH, Party.buyer_mail_zip4).send_keys("2134")
driver.save_screenshot("./screenshots/buyer_party_page.png")
add_time('./screenshots/buyer_party_page.png')
time.sleep(5)
# driver.find_element(By.XPATH, Auto.autoform_submit).click()
driver.close()
driver.switch_to.window(driver.window_handles[0])
driver.close()

