class Auto:
    recording_date = "//label[contains(text(),' Recording Date ')]/..//input"
    book = "//label[contains(text(),' Book ')]/..//input"
    page = "//label[contains(text(),' Page ')]/..//input"
    document_number = "//label[contains(text(),' Document Number ')]/..//input"
    state = "//label[contains(text(), ' State ')]/..//input"
    county_name = "//label[contains(text(), ' County Name ')]/..//input"
    fips = "//label[contains(text(), ' FIPS ')]/..//input"
    data_entry_date = "//label[contains(text(), ' Data Entry Date ')]/..//input"
    record_id = "//label[contains(text(), ' Record Id ')]/..//input"
    record_type = "//label[contains(text(), ' Record Type ')]/..//input"
    data_source_code = "//label[contains(text(), ' Data Source Code ')]/..//input"
    autoform_submit = "//button[contains(text(), ' Submit ')]"
    enter_reason = "//*[@id='formly_712_textarea_reason_0']"
    enter_reason_save = "(//button[contains(text(), 'Save')])[2]"
