class Header:
    header_form = "//a[contains(text(), 'Header Form')]"
    contract_date = "//label[contains(text(), ' Contract Date ')]/..//input"
    sales_price = "//label[contains(text(), ' Sales Price (Whole $ only) ')]/..//input"
    sales_price_code = "//label[contains(text(), ' Sales Price Code ')]/..//select"
    city_transfer_tax = "//label[contains(text(), ' City Transfer Tax ')]/..//input"
    county_transfer_tax = "//label[contains(text(), ' County Transfer Tax ')]/..//input"
    total_transfer_tax = "//label[contains(text(), ' Total Transfer Tax ')]/..//input"
    title_company_name = "(//label[contains(text(), ' Title Company Name ')]/..//input)[1]"
    wa_excise_tax = "//label[contains(text(), ' WA Excise Tax ')]/..//input"
    mtg_due_date = "//label[contains(text(),  'Mtg: Due Date (MMDDCCYY) ')]/..//input"
    mtg_interest_rate = "//label[contains(text(),  ' Mtg: Interest Rate (9999) ')]/..//input"
    mtg_lender_name = "//label[contains(text(),  ' Mtg: Lender Name (Beneficiary)')]/..//input"
    mtg_loan_amount = "//label[contains(text(),  ' Mtg: Loan Amount')]/..//input"
    mtg_loan_type = "//label[contains(text(),  ' Mtg: Loan Type')]/..//select"
    mtg_type_financing = "//label[contains(text(),  ' Mtg: Type Financing')]/..//select"
    doc_bkpg_concurrent_mortgage = "//label[contains(text(),  ' Doc # or Bk/Pg from Concurrent Mortgage ')]/..//input"
    lender_mail_zip = "(//label[contains(text(), ' Lender Mail: Zip Code ')]/..//input)[1]"
    interest_only_flag = "//label[contains(text(),  'Interest only flag')]/..//input"
    family_rider_1_4 = "//input[@id='formly_886_checkbox_riFamilyRider_0']"
    adjustable_rate_rider = "//input[@id='formly_886_checkbox_riAdjustableRateRider_1']"
    assumability_rider = "//input[@id='formly_886_checkbox_riAssumabilityRider_2']"
    balloon_rider = "//input[@id='formly_886_checkbox_riBalloonRider_3']"
    biweekly_payment_rider = "//input[@id='formly_886_checkbox_riBiweeklyPaymentRider_4']"
    condominium_rider = "//*[@id='formly_886_checkbox_riCondominiumRider_5']"
    prepayment_rider = "//*[@id='formly_886_checkbox_riPrepaymentRider_6']"
    rate_improvement_rider = "//*[@id='formly_886_checkbox_riRateImprovementRider_7']"
    second_home_rider = "//*[@id='formly_886_checkbox_riSecondHomeRider_8']"
    planned_unit_development_rider = "//*[@id='formly_886_checkbox_riPlannedUnitDevelopmentRider_9']"
    first_change_date = "//label[contains(text(), ' First Change Date - MMDDYY ')]/..//input"
    change_date_greater = "//label[contains(text(), ' 1st Change Date: Int Rate Not Greater Than (9999) ')]/..//input"
    change_date_less_than = "//label[contains(text(), ' 1st Change Date: Int Rate Not Less Than (9999) ')]/..//input"
    change_index = "//label[contains(text(), ' Change Index (9999) ')]/..//input"
    maximum_interest_rate = "//label[contains(text(), ' Maximum Interest Rate (9999) ')]/..//input"
    adj_rate_index = "//label[contains(text(), ' ADJ Rate Index ')]/..//select"
    rate_change_frequency = "//label[contains(text(), ' Rate Change Frequency ')]/..//select"
    fixed_step_rate_rider = "//label[contains(text(), ' Fixed/Step (Conversion) Rate Rider ')]/..//select"
    attorney_name = "//label[contains(text(), ' Attorney Name ')]/..//input"
    attorney_name_list = "//label[contains(text(), ' Attorney Name List ')]/..//input"
    escrow_number = "//label[contains(text(), ' Escrow Number ')]/..//input"
    escrow_officer_intials = "//label[contains(text(), ' Escrow Officer Initials ')]/..//input"
    title_company_department = "//label[contains(text(), ' Title Company - Department ')]/..//input"
    title_company_2010 = "//label[contains(text(), ' Title Company (phased in December 2010) ')]/..//input"
    title_company_branch_location = "//label[contains(text(), ' Title Company Branch Location ')]/..//input"
    title_company_name_shown_on_document = "//label[contains(text(), ' Title Company Name keyed as shown on document ')]/..//input"
    title_company_name_selected_from_list_or_parsed = "//label[contains(text(), ' Title Company Name selected from list or parsed ')]/..//input"
    title_company_name_source_code = "//label[contains(text(), ' Title Company Name Source Code (Field #98) ')]/..//input"
    title_only = "//label[contains(text(), ' Title Only ')]/..//input"
    title_order_number = "//label[contains(text(), ' Title Order Number ')]/..//input"
    adjustable_rider = "//b[contains(text(), 'Adjustable Rider')]/..//button/i"

