class Legal:
    legal_form = "//a[contains(text(), 'Legal Form')]"
    portion_of_apn = "//*[@id='formly_915_checkbox_portionAPN_0']"
    supplemental_apn = "//*[@id='formly_915_checkbox_supplementalAPN_1']"
    multiple_tax = "//*[@id='formly_915_checkbox_multipleTax_2']"
    apn_1st = "(//input[contains(@id,'custom-input_apnOrPinNumber_0')])[1]"
    add_apn = "(//button[contains(text(), ' Add ')])[1]"
    apn_2nd = "(//input[contains(@id,'custom-input_apnOrPinNumber_0')])[2]"
    tax_id_number = "//label[contains(text(), ' Tax ID Number ')]/..//input"
    property_address = "//input[contains(@id, 'custom-input_propertyStreetAddress')]"
    property_unit = "(//input[contains(@id, 'custom-input_propertyUnit')])[1]"
    property_city = "(//input[contains(@id, 'custom-input_propertyCity_2')])[1]"
    property_state = "(//select[contains(@id, 'select_propertyState_3')])[1]"
    property_zip = "(//input[contains(@id, 'custom-input_propertyZip_4')])[1]"
    property_zip4 = "(//input[contains(@id, 'custom-input_propertyZip4_5')])[1]"
    property_add = "(//button[contains(text(), ' Add ')])[2]"
    legal_lot = "(//input[contains(@id, 'custom-input_legalLotNumber_0')])[1]"
    legal_block = "(//input[contains(@id, 'custom-input_legalBlock_1')])[1]"
    legal_section = "(//input[contains(@id, 'custom-input_legalSection_2')])[1]"
    legal_unit = "(//input[contains(@id, 'custom-input_legalUnit_3')])[1]"
    legal_phase_number = "(//input[contains(@id, 'custom-input_legalPhase_4')])[1]"
    legal_subdivision = "(//input[contains(@id, 'custom-input_legalSubdivisionName_5')])[1]"
    legal_map_reference = "(//input[contains(@id, 'custom-input_recorderMapReference_6')])[1]"
    legal_city_muni_town = "(//input[contains(@id, 'custom-input_legalCityMuniTown_7')])[1]"
    legal_tract_number = "(//input[contains(@id, 'custom-input_legalTract_8')])[1]"
    legal_district = "(//input[contains(@id, 'custom-input_legalDistrict_9')])[1]"
    legal_land_lot = "(//input[contains(@id, 'custom-input_legalLandLot_10')])[1]"
    legal_brief_desc = "(//input[contains(@id, 'custom-input_legalBriefDescription_11')])[1]"
    legal_section_twn_range_merid = "(//input[contains(@id, 'custom-input_legalSectionTwnRangeMerid_12')])[1]"
    legal_lot_code = "(//select[contains(@id, 'select_legalLotCode_13')])[1]"
    legal_add = "(//button[contains(text(), ' Add ')])[3]"
    property_use_code = "//select[contains(@id, 'select_propertyUseCode_1')]"
    Lot_size_acreage = "//input[contains(@id, 'custom-input_lotSizeAcreage_2')]"
    property_buyer_macode = "//select[contains(@id, 'select_propertyMailingAddressCode_3')]"
    complete_legal_desc_code = "//select[contains(@id, 'select_completeLegalDescriptionCode_4')]"
    partial_interest_transferred = "//select[contains(@id, 'select_partialInterestTransferred_5')]"
